feat: initial tooling for migrating D1 data to Dynamo
web3-storage/w3infra pull request #204
Opened 2023-06-14 01:09 UTC by travis

to run:

```
cd tools/d1-migration
chmod +x fetch-data-from-d1.sh
./fetch-data-from-d1.sh
cd ../
ENV=staging node cli.js d1-migration
```

currently just prints out the dynamo commands it will run, needs testing in PR env

2023-07-12 06:19 UTC, Gozala approved these changes

2023-07-12 09:08 UTC, vasco-santos requested changes
wrong button 😓

2023-07-12 09:13 UTC, vasco-santos reviewed
migration code looks good, a couple of extra suggestions:

1. Could we add a Github action dispatch workflow that would run this? it can receive as input the stage and is a good way to test with a environment that will be the same for both stages
2. Should we have a validation step as well that checks that all expected content is there in expected format? Maybe read again D1 and do Dynamo Gets as needed

2023-07-13 07:17 UTC, vasco-santos commented
> @vasco-santos would you be ok with not doing this? I'd like to timebox it because it doesn't add a ton of value over just running this manually on my machine for the one time we'll ever need to run this migration.

Yes, I suggested as a way to decouple from a specific environment and anyone could run. But was expecting it to be just adding the workflow to run 

```sh
cd tools/d1-migration
chmod +x fetch-data-from-d1.sh
./fetch-data-from-d1.sh
cd ../
STAGE=pr194 node cli.js d1-migration
```

Given now context increased to also run wrangler commands that seems good

2023-07-13 18:11 UTC, merged